estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace='home')),
    path('houses/', include("houses.urls", namespace='houses')),
    path('land/', include("land.urls", namespace='land')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
]

admin.site.site_header = "La Tenuta Admin"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

    path('', views.homepage, name='home'),

]

land/urls.py
from django.urls import re_path

from . import views


app_name = 'land'

urlpatterns = [

    re_path(r'^data/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.parcel_data, name='landsData'),
    re_path(r'^$', views.parcel_list, name='parcel_list'),
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.parcel_list, name='parcel_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.parcel_detail, name='parcel_detail'),

]

land/models.py
from django.contrib.gis.db import models

from django.urls import reverse

from django.utils import timezone


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('land:parcel_list_by_category', args=[self.slug])


class County(models.Model):
    objectid = models.BigIntegerField()
    unit_area = models.FloatField()
    unit_perim = models.FloatField()
    district = models.CharField(max_length=50)
    count_field = models.FloatField()
    county_nam = models.CharField(max_length=50, db_index=True)
    code = models.IntegerField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)

    class Meta:
        ordering = ('county_nam',)
        verbose_name = 'county'
        verbose_name_plural = "counties"

    def __str__(self):
        return self.county_nam

    def get_absolute_url(self):
        return reverse('land:parcel_list_by_county', args=[self.county_nam])


class District(models.Model):
    distname = models.CharField(max_length=20, db_index=True)
    geom = models.MultiPolygonField(srid=4326)

    class Meta:
        ordering = ('distname',)
        verbose_name = 'district'
        verbose_name_plural = "districts"

    def __str__(self):
        return self.distname


class Parcel(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    owner = models.CharField(max_length=300, db_index=True)
    title_number = models.CharField(max_length=70)
    area = models.FloatField(max_length=5)
    county = models.ForeignKey(County, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    geometry = models.PolygonField(srid=4326, geography=True)
    photo = models.ImageField(upload_to='parcels/%Y/%m/%d')
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='Parcels')
    price = models.DecimalField(max_digits=15, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('-added',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('land:parcel_detail', args=[self.id, self.slug])

land/views.py
from django.shortcuts import render, get_object_or_404
from django.core.serializers import serialize
from django.http import HttpResponse
from .models import Parcel, Category
from django.db.models import Q


# Create your views here.


def parcel_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    parcels = Parcel.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        parcels = parcels.filter(category=category)
    query = request.GET.get('query')
    if query:
        parcels = Parcel.objects.filter(
            Q(name__icontains=query) |
            Q(title_number__icontains=query) |
            Q(description__icontains=query)
        ).distinct()
        if parcels.count() > 0:
            return render(request, 'land/land.html',
                          {'category': category, 'categories': categories, 'parcels': parcels})
        else:
            print('The parcel you searched for does not exist in our databases. I will look into this searches need to'
                  ' have some inspiration. They never return zero matches')
    return render(request, 'land/land.html', {'category': category, 'categories': categories, 'parcels': parcels})


def parcel_detail(request, id, slug):
    parcel = get_object_or_404(Parcel, id=id, slug=slug, available=True)
    return render(request, 'land/parcel.html', {'parcel': parcel})


def parcel_data(request, id, slug):
    parcels = serialize(
        'geojson',
        Parcel.objects.filter(id=id, slug=slug),
        geometry_field='geometry',
        fields='geometry')
    return HttpResponse(parcels, content_type='json')


#serialize('geojson', Parcel.objects.filter(id=id),
          #geometry_field='geom',
          #fields=('name', 'description',))

templates/land/land.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <header>
            <h1>{% if category %}{{ category.name }}{% else %}Parcels{% endif %}</h1>
        </header>

        <div class="row justify-content-md-right">
            <div id="sidebar" class="col col-lg-2 panel panel-success">
                <h3>Categories</h3>
                <ul class="nav nav-tabs nav-stacked">
                    <li {% if not category %}class=""{% endif %}>
                        <a href="{% url 'land:parcel_list' %}">All</a>
                    </li>
                    {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div id="main" class="col-lg-6 panel panel-primary justify-content-lg-center">
                <h1>{% if category %}{{ category.name }}{% else %}Parcels{% endif %}</h1>
                <form method="GET" action="">
                    {% csrf_token %}
                    <input type="text" name="query" value="{{ request.GET.query }}" placeholder="Search parcels...">
                    <input type="submit" value="Search">
                </form>
                <br>
                {% for parcel in parcels %}
                    <a href="{{ parcel.get_absolute_url }}">
                        <img class="img-responsive img-thumbnail" src="{% if parcel.photo %}{{ parcel.photo.url }}{% else %}{% static 'img/No_Image_Available.jpg'%}{% endif %}">
                    </a><br>
                    <h2><a href="{{ parcel.get_absolute_url }}">{{ parcel.name }}</a></h2>
                    <h3>Title Number: {{ parcel.title_number }}</h3>
                    <h3>Approximate area: {{ parcel.area }} Ha</h3>
                    <h2>Ksh. {{ parcel.price }}</h2>
                    <div class="">
                        <h3>County: {{ parcel.county }}</h3>
                        <h3>District: {{ parcel.district }}</h3>
                        <h3></h3>
                    </div>
                    <br>
                    <hr>
                    <br>

                {% endfor %}
            </div>
        </div>

    </div>

    {% include 'footer.html' %}

{% endblock %}

templates/land/parcel.html
{% extends "base.html" %}
{% load static %}
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-groupedlayercontrol/0.6.1/leaflet.groupedlayercontrol.css" integrity="sha512-PpKEvRG//V8hN9idekL4WOjknpMTPFH3MnWpVbVBmlzXpoUfbBSr054U/TUmOzUnCOM9PAPiLhRgq0i00B4q3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />{% endblock %}
{% block content %}
    <br><br>
    <div class="container-fluid">
        <div class="col-md-6">
            <br>
            <img class="img-responsive img-thumbnail" src="{% if parcel.photo %}{{ parcel.photo.url }}{% else %}{% static "img/No_Image_Available.jpg" %}{% endif %}">
            <h1 class="">{{ parcel.name }}</h1>
            <h2><a href="{{ parcel.category.get_absolute_url }}">{{ parcel.category }}</a> </h2>
            <p class="price">Ksh {{ parcel.price }}</p>

            <p>{{ parcel.county }} county<br>
                District:{{ parcel.district }}
            </p>
            <div class="panel panel-info">
                <p>{{ parcel.description|linebreaks }}</p>
            </div>
            <button type="button" class="btn btn-success btn-outline-success"><a href="{% url 'land:landsData' parcel.id parcel.slug %}">Buy</a></button>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Launch demo modal
            </button>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            ...
                            <p>I was trying out this bootstrap feature. In the future I could use it for enabling buying
                                . In the meantime I'm using it to display the geometric data. Just practising it's never
                                that serious.
                            </p>
                            ...
                            <br>
                            <a href="{% url 'land:landsData' parcel.id parcel.slug %}">Serialized Geometric Data</a>
                            <br>
                            ...
                            <br>
                            <a href="{{ parcel.geometry.get_absolute_url }} ">{{ parcel.geometry }}</a>
                            <br>
                            ...
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="panel panel-success col-md-6 col-offset-md-6">
            <br>
            <div id="map" class="panel-body leaflet-map-pane" style="height: 500px">
                <script type="text/javascript">
                    function layers(map) {
                        var osm = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';
                        var data  = new L.GeoJSON.AJAX("{% url 'land:landsData' parcel.id parcel.slug %}", {
                            onEachFeature: function (feature, layer) {
                                layer.bindPopup(
                                    feature.properties.name.toString()
                                );
                            }
                        });
                        data.addTo(map);
                        map.panTo(data);
                        var baseLayers = {
                            "OSM": osm
                        };
                        var groupedOverlays = {
                            "Parcel":{
                                "Parcel": data
                            }
                        };
                        L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);
                    }
                </script>
                {% leaflet_map "map" callback="window.layers" %}
            </div>
            <br>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/0.2.0/leaflet.ajax.min.js" integrity="sha512-rQ5LOlEFAvCjdd93ybsBPYGy2rSiTeciSGFxl1VFcP3uy3rtrw+cyr/9Zp0Bm0mAO2uawkZycc0LBft7DbfREQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-groupedlayercontrol/0.6.1/leaflet.groupedlayercontrol.min.js" integrity="sha512-cdomNfv1IRJE1v+2/irZdkNU09XwtYP2bQ1qK1ybWF/vz+P3GTMZtrXwlxTU41ExwoWGvEf0njIak5l/ZQaIMA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>{% endblock %}
{% block footer %}
{% include 'footer.html' %}
{% endblock %}