estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace='home')),
    path('houses/', include("houses.urls", namespace='houses')),
    path('land/', include("land.urls", namespace='land')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
]

admin.site.site_header = "La Tenuta Admin"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

    path('', views.homepage, name='home'),

]

houses/urls.py
from django.urls import re_path

from . import views

app_name = 'houses'

urlpatterns = [

    re_path(r'^data/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.house_data, name='houseData'),
    re_path(r'^$', views.house_list, name='house_list'),
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.house_list, name='house_list_by_type'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.house_detail, name='house_detail'),

]

houses/models.py
from django.contrib.gis.db import models

from django.urls import reverse


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'type'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('houses:house_list_by_type', args=[self.slug])


class County(models.Model):
    objectid = models.BigIntegerField()
    unit_area = models.FloatField()
    unit_perim = models.FloatField()
    district = models.CharField(max_length=50)
    count_field = models.FloatField()
    county_nam = models.CharField(max_length=50)
    code = models.IntegerField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.county_nam

    class Meta:
        ordering = ('county_nam',)
        verbose_name = 'county'
        verbose_name_plural = 'counties'

    def get_absolute_url(self):
        return reverse('land:parcel_list_by_county', args=[self.county_nam])


class District(models.Model):
    distname = models.CharField(max_length=20, db_index=True)
    geom = models.MultiPolygonField(srid=4326)

    class Meta:
        ordering = ('distname',)
        verbose_name = 'district'
        verbose_name_plural = "districts"

    def __str__(self):
        return self.distname


class House(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='Houses')
    name = models.CharField(max_length=250, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, )
    available = models.BooleanField(default=True)
    time_added = models.DateTimeField(auto_now_add=True)
    county = models.ForeignKey(County, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    geometry = models.PolygonField(srid=4326)
    description = models.TextField()
    photo = models.ImageField(upload_to='houses/%Y/%m/%d')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-time_added',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('houses:house_detail', args=[self.id, self.slug])

houses/views.py
from django.shortcuts import render, get_object_or_404
from django.core.serializers import serialize
from django.http import HttpResponse
from .models import House, Category
from django.db.models import Q


# Create your views here.


def house_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    houses = House.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        houses = houses.filter(category=category)
    query = request.GET.get('query')
    if query:
        houses = House.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        ).distinct()
    return render(request, 'houses/houses.html', {'category': category, 'categories': categories, 'houses': houses})


def house_detail(request, id, slug):
    house = get_object_or_404(House, id=id, slug=slug, available=True)
    return render(request, 'houses/detail.html', {'house': house})


def house_data(request, id, slug):
    house = serialize('geojson', House.objects.filter(id=id, slug=slug))
    return HttpResponse(house, content_type='json')

templates/houses/detail.html
{% extends "base.html" %}
{% load static %}
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-groupedlayercontrol/0.6.1/leaflet.groupedlayercontrol.css" integrity="sha512-PpKEvRG//V8hN9idekL4WOjknpMTPFH3MnWpVbVBmlzXpoUfbBSr054U/TUmOzUnCOM9PAPiLhRgq0i00B4q3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />{% endblock %}
{% block content %}
    <br><br>
    <div class="container-fluid">
        <div class="col-md-6">
            <br>
            <img class="img-responsive img-thumbnail" src="{% if house.photo %}{{ house.photo.url }}{% else %}{% static "img/No_Image_Available.jpg" %}{% endif %}">
            <h1 class="">{{ house.name }}</h1>
            <h2><a href="{{ house.category.get_absolute_url }}">{{ house.category}}</a> </h2>
            <p class="price">Ksh {{ house.price }}</p>

            <p>{{ house.county }} county<br>
                District:{{ house.district }}
            </p>
            <div class="panel panel-info">
                <p>{{ house.description|linebreaks }}</p>
            </div>
            <button type="button" class="btn btn-success btn-outline-success"><a href="{% url 'houses:houseData' house.id house.slug %}">Buy</a></button>
        </div>
        <br>
        <div class="panel panel-success col-md-6 col-offset-md-6">
            <br>
            <div id="map" class="panel-body leaflet-map-pane" style="height: 500px">
                <script type="text/javascript">
                    function layers(map) {
                        var osm = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';
                        var data  = new L.GeoJSON.AJAX("{% url 'houses:houseData' house.id house.slug %}", {
                            onEachFeature: function (feature, layer) {
                                layer.bindPopup(
                                    feature.properties.name.toString(),
                                    feature.properties.description.toString()
                                );
                            }
                        });
                        data.addTo(map);
                        var baseLayers = {
                            "OSM": osm
                        };
                        var groupedOverlays = {
                            "Parcel":{
                                "Parcel": data
                            }
                        };
                        L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);
                    }
                </script>
                {% leaflet_map "map" callback="window.layers" %}
            </div>
            <br>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/0.2.0/leaflet.ajax.min.js" integrity="sha512-rQ5LOlEFAvCjdd93ybsBPYGy2rSiTeciSGFxl1VFcP3uy3rtrw+cyr/9Zp0Bm0mAO2uawkZycc0LBft7DbfREQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-groupedlayercontrol/0.6.1/leaflet.groupedlayercontrol.min.js" integrity="sha512-cdomNfv1IRJE1v+2/irZdkNU09XwtYP2bQ1qK1ybWF/vz+P3GTMZtrXwlxTU41ExwoWGvEf0njIak5l/ZQaIMA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>{% endblock %}
{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/houses/houses.html
{% extends 'base.html' %}
{% load static %}


{% block header %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <header>
            <h1>{% if category %}{{ category.name }}{% else %}Houses{% endif %}</h1>
        </header>
        <div class="row justify-content-md-right">
            <div id="sidebar" class="col col-lg-2 panel panel-success">
                <h3>Type</h3>
                <ul class="nav nav-tabs nav-stacked">
                    <li {% if not category %}class="selected"{% endif %}>
                        <a href="{% url 'houses:house_list' %}">All</a>
                    </li>
                    {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div id="main" class="col-lg-6 panel panel-primary justify-content-lg-center">
                <h1>{% if category %}{{ category.name }}{% else %}Houses{% endif %}</h1>
                <form method="GET" action="">
                    {% csrf_token %}
                    <input type="text" name="query" value="{{ request.GET.query }}" placeholder="Search for a house...">
                    <input type="submit" value="Search">
                </form>
                <br>
                {% for house in houses %}
                    <a href="{{ house.get_absolute_url }}">
                        <img class="img-thumbnail img-responsive" src="{% if house.photo %}{{ house.photo.url }}{% else %}{% static 'img/No_Image_Available.jpg'%}{% endif %}">
                    </a><br>
                    <h2><a href="{{ house.get_absolute_url }}">{{ house.name }}</a></h2>
                    <h2>Ksh {{ house.price }}</h2>
                    <div class="panel panel-info">
                        <h3>County: {{ house.county }}</h3>
                    </div>
                    <br>
                    <hr>
                    <br>

                {% endfor %}
            </div>
        </div>

    </div>

    {% include 'footer.html' %}

{% endblock %}