accounts/urls.py
from django.urls import path, re_path

from accounts import views as accounts_views

from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [

    path('add/', accounts_views.register_user, name='add'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),

    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='password_reset_email.html',
                                                        subject_template_name='password_reset_subject.txt'),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
            name='password_reset_confirm'),

    path('reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),

    path('settings/password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

]

estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace='home')),
    path('houses/', include("houses.urls", namespace='houses')),
    path('land/', include("land.urls", namespace='land')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
]

admin.site.site_header = "La Tenuta Admin"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

    path('', views.homepage, name='home'),

]

houses/urls.py
from django.urls import re_path

from . import views

app_name = 'houses'

urlpatterns = [

    re_path(r'^data/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.house_data, name='houseData'),
    re_path(r'^$', views.house_list, name='house_list'),
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.house_list, name='house_list_by_type'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.house_detail, name='house_detail'),

]

land/urls.py
from django.urls import re_path

from . import views


app_name = 'land'

urlpatterns = [

    re_path(r'^data/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.parcel_data, name='landsData'),
    re_path(r'^$', views.parcel_list, name='parcel_list'),
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.parcel_list, name='parcel_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.parcel_detail, name='parcel_detail'),

]

templates/base.html
{% load static %}
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Latest (3.3.6) compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link href="{% static 'estate/css/estate.css' %}" rel="stylesheet" type="text/css">
        <link rel="icon" href="{% static 'img/portfolio/fullsize/2.jpg' %}" >
        <title>{% block title %}La Tenuta{% endblock %}</title>
    </head>
    <body>
    {% block header %}
    {% endblock %}
    {% block navbar %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
<!--Javascript goes down here for faster page loading
===================================================== -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% comment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    {% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous">
    </script>

</body>

</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'estate/css/estate.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home:home' %}">La Tenuta</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/footer.html
<footer class="modal-footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted align-items-center">
            &copy; La Tenuta 2018
        </p>
      </div>
        <div class="text-center">
            &copy; La Tenuta 2018
        </div>
    </div>
  </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'home:home' %}">La Tenuta</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'land:parcel_list' %}">Land</a></li>
                        <li><a href="{% url 'houses:house_list' %}">Housing</a></li>
                        <li><a href="#">About</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                <div class="dropdown">
                     <li class="nav-item glyphicon glyphicon-user btn text-capitalize text-success btn-outline-success" type="" data-toggle="dropdown">
                        {{ user.username }}
                        <span class="caret"></span>
                    </li>
                    <ul class="dropdown-menu">
                        <li><a href="#">Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'accounts:password_reset' %}">Reset password</a></li>
                        <li><a href="{% url 'accounts:password_change' %}">Change password</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    </ul>
                </div>
            {% else %}
                <ul class="nav navbar-nav">
                    <li class=""><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'land:parcel_list' %}">Land</a></li>
                    <li><a href="{% url 'houses:house_list' %}">Housing</a></li>
                    <li><a href="#">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'accounts:add' %}"><span class="glyphicon glyphicon-user"></span> Signup</a></li>
                </ul>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your La Tenuta username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

La Tenuta Team